
resources:
  - name: dh_image
    type: Image
    configuration:
      registry: dockerhub
      imageName: nginx
      imageTag: latest
  - name: docker_image
    type: Image
    configuration:
      registry: Art1
      sourceRepository: docker
      imageName: 35.244.19.217:8081/docker/busybox
      imageTag: latest
  - name: dockerbuild_repo
    type: GitRepo
    configuration:
      path: balajils1/Sampleproject
      gitProvider: balaji
  - name: docker_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: Art1
      buildName: docker_example
      buildNumber: 1
  - name: files
    type: FileSpec
    configuration:
      sourceArtifactory: Art1
      pattern: generic-local/*
      
pipelines:
  - name: docker_example
    steps:
      - name: build_docker
        type: DockerBuild
        configuration:
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: 35.244.19.217:8081/docker/balaji
          dockerImageTag: $pipeline_name.$run_number
          inputResources:
            - name: dockerbuild_repo
            #- name: docker_image
            - name: files
            - name: dh_image
          integrations:
            - name: Art1
      - name: push_docker_image
        type: DockerPush
        configuration:
          targetRepository: docker
          integrations:
            - name: Art1
          inputSteps:
            - name: build_docker
      - name: publish_docker_build
        type: PublishBuildInfo
        configuration:
         # integrations:
          #  - name: Art1
          inputSteps:
            - name: push_docker_image
          outputResources:
            - name: docker_build_info
