
resources:
  - name: npmHelloWorld_repo
    type: GitRepo
    configuration:
      gitProvider: balaji
      path: balajils1/Sampleproject
  - name: helloworld_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: Art1
      buildName: npm_example
      buildNumber: 1
      
pipelines:
  - name: npm_example
    steps:
      - name: build_npm
        type: NpmBuild
        configuration:
          repositoryName: npm
          sourceLocation: .
          inputResources:
            - name: npmHelloWorld_repo
          integrations:
            - name: Art1
      - name: publish_npm
        type: NpmPublish
        configuration:
          repositoryName: npm-local
          inputSteps:
            - name: build_npm
          integrations:
            - name: Art1
      - name: publish_build_info
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: publish_npm
          #integrations:
           # - name: Art1
          outputResources:
            - name: helloworld_build_info
      - name: scan
        type: XrayScan
        configuration:
           #inherits from bash
          inputResources:
            - name: helloworld_build_info
              trigger: true
          waitUntilFinish: true
